# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bliss Apiary Objective-C' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bliss Apiary Objective-C
  pod 'AFNetworking', '~> 3.0'
  pod 'DGActivityIndicatorView'
  pod 'IQKeyboardManager'

end
